---
title: "R Notebook"
output: html_notebook
---

In this report we are going to look at the question if movies from the 2000s with a higher budget also have a higher revenue. The variables we thus have to look at are the budgets and revenues. The data used to answer this question is acquired from the IMDB site. The data frame contains columns with id, IMDB id', title of the movie, decade and much more. To answer the question we will plot the variables of budget and revenue in a scatterplot. We will therfore use points as geoms.

```{r}
library(tidyverse)
# Firstly, we have to filter out the correct decade, the 2000s, from the data file. Therefore, we need to use the filter function

movies_correcr <- movies %>% #creates a new data file
  filter(decade== "2000s")#with only movies from th 2000s

#The variables that wwe want to plot against each other are budget and revenue, we will now plot these with the geom_point function

ggplot() +
  geom_point(
    data = movies_correcr, #select the correct data file
    mapping = aes(x = budget, y = revenue) #assigning  x and y variable
  ) + # adding a title
  ggtitle("The relation between revenue and budget of 2000s movies") 
  
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.


Blababaka no figure